### ISSUE TITLE
plinkfile import error due to GLIBC.214

### ISSUE THREAD

**Issue by sn-GT** [mfranberg/libplinkio#20]
Hi 
I have been succesfully able to install plinkio. However, when I import plinkfile, I get import error from cplinkio - glibc2.14 (see error below). How do I proceed with it ?

>>> import ldpred
>>> import plinkio
>>> from plinkio import plinkfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nv/hp10/snagpal3/.conda/envs/ldpred/lib/python3.6/site-packages/plinkio/plinkfile.py", line 1, in <module>
    from . import cplinkio
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /nv/hp10/snagpal3/.conda/envs/ldpred/lib/python3.6/site-packages/plinkio/cplinkio.cpython-36m-x86_64-linux-gnu.so)

On running the command below, it shows that I have GLIBC on my system:
strings /lib64/libc.so.6|grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

Thanks

**Comment by mfranberg** [comment]
This issue has become stale so I will close it, please reopen if the problem remains.
